@extends('admin.layouts.app', [
    'pageTitle' => 'База на кандидати',
    'pageDescription' => 'Приватна база на кандидати, достапна само за администратори.',
])

@section('content')
    @php
        $genders = \App\Models\CandidateProfile::genderOptions();
        $radii = \App\Models\CandidateProfile::radiusOptions();
        $driving = \App\Models\CandidateProfile::drivingStatusOptions();
        $engagements = \App\Models\CandidateProfile::engagementTypeOptions();
        $categories = \App\Models\CandidateProfile::workCategoryOptions();
        $statuses = \App\Models\CandidateProfile::statusOptions();
    @endphp

    <div class="mb-6 rounded-[1.6rem] bg-white p-6 shadow-[0_20px_45px_-34px_rgba(15,23,42,0.2)]">
        <div class="mb-5 flex flex-wrap items-center justify-between gap-3"><p class="text-sm font-semibold text-slate-700">Вкупно пронајдени: {{ $profiles->total() }}</p><a href="{{ route('admin.candidates.index') }}" class="text-sm font-semibold text-emerald-700 hover:text-emerald-600">Исчисти филтри</a></div>
        <form method="GET" action="{{ route('admin.candidates.index') }}" class="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
            <input name="search" value="{{ $filters['search'] ?? '' }}" placeholder="Име, телефон или email" class="rounded-2xl border-slate-200 px-4 py-3 text-sm focus:border-emerald-500 focus:ring-emerald-100">
            <select name="city" class="rounded-2xl border-slate-200 px-4 py-3 text-sm focus:border-emerald-500 focus:ring-emerald-100"><option value="">Сите градови</option>@foreach ($cities as $city)<option value="{{ $city }}" @selected(($filters['city'] ?? '') === $city)>{{ $city }}</option>@endforeach</select>
            <input name="neighbourhood" value="{{ $filters['neighbourhood'] ?? '' }}" placeholder="Населба" class="rounded-2xl border-slate-200 px-4 py-3 text-sm focus:border-emerald-500 focus:ring-emerald-100">
            <select name="gender" class="rounded-2xl border-slate-200 px-4 py-3 text-sm focus:border-emerald-500 focus:ring-emerald-100"><option value="">Сите полови</option>@foreach ($genders as $value => $label)<option value="{{ $value }}" @selected(($filters['gender'] ?? '') === $value)>{{ $label }}</option>@endforeach</select>
            <input name="min_age" type="number" min="0" max="120" value="{{ $filters['min_age'] ?? '' }}" placeholder="Минимална возраст" class="rounded-2xl border-slate-200 px-4 py-3 text-sm focus:border-emerald-500 focus:ring-emerald-100">
            <input name="max_age" type="number" min="0" max="120" value="{{ $filters['max_age'] ?? '' }}" placeholder="Максимална возраст" class="rounded-2xl border-slate-200 px-4 py-3 text-sm focus:border-emerald-500 focus:ring-emerald-100">
            <select name="driving_status" class="rounded-2xl border-slate-200 px-4 py-3 text-sm focus:border-emerald-500 focus:ring-emerald-100"><option value="">Сите возачки статуси</option>@foreach ($driving as $value => $label)<option value="{{ $value }}" @selected(($filters['driving_status'] ?? '') === $value)>{{ $label }}</option>@endforeach</select>
            <select name="current_employment_status" class="rounded-2xl border-slate-200 px-4 py-3 text-sm focus:border-emerald-500 focus:ring-emerald-100"><option value="">Сите работни статуси</option><option value="1" @selected(($filters['current_employment_status'] ?? null) === true || ($filters['current_employment_status'] ?? '') === '1')>Вработен/а</option><option value="0" @selected(($filters['current_employment_status'] ?? null) === false || ($filters['current_employment_status'] ?? '') === '0')>Не е вработен/а</option></select>
            <select name="preferred_radius" class="rounded-2xl border-slate-200 px-4 py-3 text-sm focus:border-emerald-500 focus:ring-emerald-100"><option value="">Сите радиуси</option>@foreach ($radii as $value => $label)<option value="{{ $value }}" @selected(($filters['preferred_radius'] ?? '') === $value)>{{ $label }}</option>@endforeach</select>
            <select name="status" class="rounded-2xl border-slate-200 px-4 py-3 text-sm focus:border-emerald-500 focus:ring-emerald-100"><option value="">Сите статуси</option>@foreach ($statuses as $value => $label)<option value="{{ $value }}" @selected(($filters['status'] ?? '') === $value)>{{ $label }}</option>@endforeach</select>
            <input name="submitted_from" type="date" value="{{ $filters['submitted_from'] ?? '' }}" class="rounded-2xl border-slate-200 px-4 py-3 text-sm focus:border-emerald-500 focus:ring-emerald-100">
            <input name="submitted_to" type="date" value="{{ $filters['submitted_to'] ?? '' }}" class="rounded-2xl border-slate-200 px-4 py-3 text-sm focus:border-emerald-500 focus:ring-emerald-100">
            <select name="sort" class="rounded-2xl border-slate-200 px-4 py-3 text-sm focus:border-emerald-500 focus:ring-emerald-100"><option value="newest">Најнови прво</option><option value="oldest" @selected(($filters['sort'] ?? '') === 'oldest')>Најстари прво</option><option value="updated" @selected(($filters['sort'] ?? '') === 'updated')>Неодамна ажурирани</option><option value="confirmed" @selected(($filters['sort'] ?? '') === 'confirmed')>Неодамна потврдени</option><option value="name" @selected(($filters['sort'] ?? '') === 'name')>Име A–Z</option><option value="youngest" @selected(($filters['sort'] ?? '') === 'youngest')>Најмлади прво</option><option value="oldest_age" @selected(($filters['sort'] ?? '') === 'oldest_age')>Највозрасни прво</option></select>
            <div class="xl:col-span-4"><p class="mb-2 text-sm font-semibold text-slate-700">Видови ангажман</p><div class="flex flex-wrap gap-3">@foreach ($engagements as $value => $label)<label class="inline-flex items-center gap-2 text-sm text-slate-600"><input type="checkbox" name="engagement_types[]" value="{{ $value }}" @checked(in_array($value, $filters['engagement_types'] ?? [], true)) class="rounded border-slate-300 text-emerald-600">{{ $label }}</label>@endforeach</div></div>
            <div class="xl:col-span-4"><p class="mb-2 text-sm font-semibold text-slate-700">Категории</p><div class="flex flex-wrap gap-3">@foreach ($categories as $value => $label)<label class="inline-flex items-center gap-2 text-sm text-slate-600"><input type="checkbox" name="work_categories[]" value="{{ $value }}" @checked(in_array($value, $filters['work_categories'] ?? [], true)) class="rounded border-slate-300 text-emerald-600">{{ $label }}</label>@endforeach</div></div>
            <div class="xl:col-span-4"><button type="submit" class="inline-flex rounded-2xl bg-emerald-600 px-6 py-3 text-sm font-semibold text-white transition hover:bg-emerald-500">Филтрирај</button></div>
        </form>
    </div>

    <div class="overflow-hidden rounded-[1.6rem] bg-white shadow-[0_20px_45px_-34px_rgba(15,23,42,0.2)]"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm"><thead class="bg-slate-50"><tr class="text-left text-slate-500"><th class="px-6 py-4 font-semibold">Име и презиме</th><th class="px-6 py-4 font-semibold">Град/населба</th><th class="px-6 py-4 font-semibold">Пол / возраст</th><th class="px-6 py-4 font-semibold">Возачка</th><th class="px-6 py-4 font-semibold">Работен статус</th><th class="px-6 py-4 font-semibold">Видови ангажман</th><th class="px-6 py-4 font-semibold">Категории</th><th class="px-6 py-4 font-semibold">Статус</th><th class="px-6 py-4 font-semibold">Пријавување</th><th class="px-6 py-4"></th></tr></thead><tbody class="divide-y divide-slate-100">@forelse ($profiles as $candidate)<tr><td class="px-6 py-4 font-semibold text-slate-900">{{ $candidate->first_name }} {{ $candidate->last_name }}</td><td class="px-6 py-4 text-slate-700">{{ $candidate->city }}<br><span class="text-slate-500">{{ $candidate->neighbourhood }}</span></td><td class="px-6 py-4 text-slate-700">{{ $genders[$candidate->gender] }}<br><span class="text-slate-500">{{ $candidate->age() }} години</span></td><td class="px-6 py-4 text-slate-700">{{ $driving[$candidate->driving_status] }}</td><td class="px-6 py-4 text-slate-700">{{ $candidate->current_employment_status ? 'Вработен/а' : 'Не е вработен/а' }}</td><td class="px-6 py-4 text-slate-700">{{ collect($candidate->engagement_types)->map(fn ($value) => $engagements[$value] ?? $value)->implode(', ') }}</td><td class="px-6 py-4 text-slate-700">{{ collect($candidate->work_categories)->map(fn ($value) => $categories[$value] ?? $value)->implode(', ') }}</td><td class="px-6 py-4 text-slate-700">{{ $statuses[$candidate->status] }}</td><td class="px-6 py-4 text-slate-500">{{ $candidate->created_at->format('d.m.Y') }}</td><td class="px-6 py-4 text-right"><a href="{{ route('admin.candidates.show', $candidate) }}" class="font-semibold text-emerald-700 hover:text-emerald-600">Отвори</a></td></tr>@empty<tr><td colspan="10" class="px-6 py-12 text-center text-slate-500">Нема кандидати што одговараат на избраните филтри.</td></tr>@endforelse</tbody></table></div><div class="border-t border-slate-100 px-6 py-4">{{ $profiles->links() }}</div></div>
@endsection
