@extends('admin.layouts.app', [
    'pageTitle' => 'Кандидат: '.$candidate->first_name.' '.$candidate->last_name,
    'pageDescription' => 'Приватен административен преглед и управување со кандидат.',
])

@section('content')
    @php
        $genders = \App\Models\CandidateProfile::genderOptions(); $radii = \App\Models\CandidateProfile::radiusOptions();
        $driving = \App\Models\CandidateProfile::drivingStatusOptions(); $statuses = \App\Models\CandidateProfile::statusOptions();
        $engagements = \App\Models\CandidateProfile::engagementTypeOptions(); $categories = \App\Models\CandidateProfile::workCategoryOptions();
    @endphp
    <div class="grid gap-6 xl:grid-cols-[1.2fr_0.8fr]">
        <form method="POST" action="{{ route('admin.candidates.update', $candidate) }}" class="rounded-[1.6rem] bg-white p-6 shadow-[0_20px_45px_-34px_rgba(15,23,42,0.2)] sm:p-8">@csrf @method('PUT')
            <h2 class="text-xl font-bold text-slate-900">Податоци и управување</h2>
            <div class="mt-6 grid gap-5 sm:grid-cols-2">
                @foreach (['first_name' => 'Име', 'last_name' => 'Презиме', 'city' => 'Град/општина', 'neighbourhood' => 'Населба', 'exact_address' => 'Точна адреса', 'email' => 'Email'] as $field => $label)<div><label for="{{ $field }}" class="mb-2 block text-sm font-semibold text-slate-700">{{ $label }}</label><input id="{{ $field }}" name="{{ $field }}" value="{{ old($field, $candidate->{$field}) }}" class="block w-full rounded-2xl border-slate-200 px-4 py-3 text-sm focus:border-emerald-500 focus:ring-emerald-100">@error($field)<p class="mt-2 text-sm text-red-600">{{ $message }}</p>@enderror</div>@endforeach
                <div><label for="gender" class="mb-2 block text-sm font-semibold text-slate-700">Пол</label><select id="gender" name="gender" class="block w-full rounded-2xl border-slate-200 px-4 py-3 text-sm">@foreach ($genders as $value => $label)<option value="{{ $value }}" @selected(old('gender', $candidate->gender) === $value)>{{ $label }}</option>@endforeach</select></div>
                <div><label for="date_of_birth" class="mb-2 block text-sm font-semibold text-slate-700">Датум на раѓање</label><input id="date_of_birth" name="date_of_birth" type="date" value="{{ old('date_of_birth', $candidate->date_of_birth?->format('Y-m-d')) }}" class="block w-full rounded-2xl border-slate-200 px-4 py-3 text-sm"></div>
                <div><label for="driving_status" class="mb-2 block text-sm font-semibold text-slate-700">Возачка дозвола</label><select id="driving_status" name="driving_status" class="block w-full rounded-2xl border-slate-200 px-4 py-3 text-sm">@foreach ($driving as $value => $label)<option value="{{ $value }}" @selected(old('driving_status', $candidate->driving_status) === $value)>{{ $label }}</option>@endforeach</select></div>
                <div><label for="preferred_radius" class="mb-2 block text-sm font-semibold text-slate-700">Радиус</label><select id="preferred_radius" name="preferred_radius" class="block w-full rounded-2xl border-slate-200 px-4 py-3 text-sm">@foreach ($radii as $value => $label)<option value="{{ $value }}" @selected(old('preferred_radius', $candidate->preferred_radius) === $value)>{{ $label }}</option>@endforeach</select></div>
                <div><label for="current_employment_status" class="mb-2 block text-sm font-semibold text-slate-700">Работен статус</label><select id="current_employment_status" name="current_employment_status" class="block w-full rounded-2xl border-slate-200 px-4 py-3 text-sm"><option value="1" @selected((bool) old('current_employment_status', $candidate->current_employment_status))>Вработен/а</option><option value="0" @selected(! (bool) old('current_employment_status', $candidate->current_employment_status))>Не е вработен/а</option></select></div>
                <div><label for="status" class="mb-2 block text-sm font-semibold text-slate-700">Статус</label><select id="status" name="status" class="block w-full rounded-2xl border-slate-200 px-4 py-3 text-sm">@foreach ($statuses as $value => $label)<option value="{{ $value }}" @selected(old('status', $candidate->status) === $value)>{{ $label }}</option>@endforeach</select></div>
                <div class="sm:col-span-2"><label for="admin_notes" class="mb-2 block text-sm font-semibold text-slate-700">Приватни admin белешки</label><textarea id="admin_notes" name="admin_notes" rows="5" class="block w-full rounded-2xl border-slate-200 px-4 py-3 text-sm">{{ old('admin_notes', $candidate->admin_notes) }}</textarea></div>
                <label class="sm:col-span-2 flex items-center gap-3 text-sm text-slate-700"><input type="checkbox" name="last_confirmed" value="1" class="rounded border-slate-300 text-emerald-600">Потврди дека податоците се проверени денес</label>
            </div><button type="submit" class="mt-7 inline-flex rounded-2xl bg-emerald-600 px-6 py-3 text-sm font-semibold text-white hover:bg-emerald-500">Зачувај промени</button>
        </form>
        <aside class="space-y-6"><div class="rounded-[1.6rem] bg-white p-6 shadow-[0_20px_45px_-34px_rgba(15,23,42,0.2)]"><h2 class="text-lg font-bold text-slate-900">Контакт и интереси</h2><dl class="mt-5 space-y-4 text-sm"><div><dt class="font-semibold text-slate-500">Телефон</dt><dd class="mt-1 text-slate-900">{{ $candidate->phone }}</dd></div><div><dt class="font-semibold text-slate-500">Видови ангажман</dt><dd class="mt-1 text-slate-900">{{ collect($candidate->engagement_types)->map(fn ($value) => $engagements[$value] ?? $value)->implode(', ') }}</dd></div><div><dt class="font-semibold text-slate-500">Категории</dt><dd class="mt-1 text-slate-900">{{ collect($candidate->work_categories)->map(fn ($value) => $categories[$value] ?? $value)->implode(', ') }}</dd></div><div><dt class="font-semibold text-slate-500">Дополнителни информации</dt><dd class="mt-1 whitespace-pre-line text-slate-900">{{ $candidate->additional_information ?: 'Нема.' }}</dd></div><div><dt class="font-semibold text-slate-500">Согласност</dt><dd class="mt-1 text-slate-900">{{ $candidate->privacy_policy_version }} · {{ $candidate->privacy_acknowledged_at?->format('d.m.Y H:i') }}</dd></div></dl></div><div class="rounded-[1.6rem] border border-red-100 bg-white p-6 shadow-[0_20px_45px_-34px_rgba(15,23,42,0.2)]"><form method="POST" action="{{ route('admin.candidates.destroy', $candidate) }}" onsubmit="return confirm('Потврди бришење на кандидатот?')">@csrf @method('DELETE')<button class="text-sm font-semibold text-red-700 hover:text-red-600">Избриши кандидат</button></form></div><a href="{{ route('admin.candidates.index') }}" class="inline-flex text-sm font-semibold text-emerald-700 hover:text-emerald-600">Назад кон база на кандидати</a></aside>
    </div>
@endsection
